#!/bin/bash
# vim: set ft=sh

set -e

ROOT_PATH=$PWD

DOT_FILES=(
  *rc
  zprofile
  zshenv
  vim
  rst2pdf
  my.cnf
  ctags
  tmux.conf
)

make_slink(){
  echo installing dotfiles...
  for file in  "${DOT_FILES[@]}"; do
    if [ -L "$HOME/.$file" ]; then
      echo "$HOME/.$file is exist"
    elif [ -e "$HOME/.$file" ]; then
      mv -v "$HOME/.$file" "$HOME/.$file.back"
      ln -vsb "$ROOT_PATH/$file" "$HOME/.$file"
    else
      ln -vs "$ROOT_PATH/$file" "$HOME/.$file"
    fi
  done
}

configure_gitignore(){
  GITIGNORE=~/.gitignore

  git config --global core.excludesfile $GITIGNORE
  tags_cnt=0
  [ -f "$GITIGNORE" ] && tags_cnt=$(grep -c "doc/tags"  $GITIGNORE)
  if [ "$tags_cnt" -eq 0 ]; then
    echo doc/tags    >> $GITIGNORE
    echo doc/tags-ja >> $GITIGNORE
  fi
}

install_vim_plug() {
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/0.10.0/plug.vim
  mkdir -p ~/.local/share/nvim/site/autoload/
  ln -vs ~/.vim/autoload/plug.vim ~/.local/share/nvim/site/autoload/
}

main() {
  git submodule update --init
  make_slink
  install_vim_plug
  vim -T dumb -c PlugInstall -c ':q' -c ':q'
  configure_gitignore
}

main
