#!/bin/bash

ROOT_PATH=$PWD

DOT_FILES=(
  *rc
  zshenv
  vim
  rst2pdf
  my.cnf
  ctags
  tigrc
)

make_slink(){
  echo install dotfiles.
  for file in  ${DOT_FILES[@]}; do
    if [ -e ~/.$file ]; then
      echo "~/.$file is exist"
    else
      ln -vs $ROOT_PATH/$file ~/.$file 
    fi
  done
}

configure_gitignore(){
  GITIGNORE=~/.gitignore

  git config --global core.excludesfile $GITIGNORE
  tags_cnt=`grep -c "doc/tags"  $GITIGNORE`
  if [ $tags_cnt -eq 0 ]; then
    echo doc/tags    >> $GITIGNORE
    echo doc/tags-ja >> $GITIGNORE
  fi
}

make_vimproc(){
  # make vimproc
  cd vim/bundle/vimproc
  if [ -e autoload/proc.so ] ;then
    cd $ROOT_PATH
    return
  fi

  echo make vimproc
  case "${OSTYPE}" in
  freebsd*|darwin*)
    make -f make_mac.mak
  ;;
  linux*)
    make -f make_gcc.mak
  ;;
  esac
  cd $ROOT_PATH
}

git submodule update --init
vim +BundleInstall +:q +:q
make_slink
configure_gitignore
make_vimproc
